export const DOM = {
  modal      : document.getElementById('modal'),
  statusDot  : document.getElementById('status-dot'),
  statusText : document.getElementById('status-text'),
  chatPanel  : document.getElementById('chat-panel'),
  chatToggle : document.getElementById('chat-toggle'),
  chatClose  : document.getElementById('chat-close'),
  messages   : document.getElementById('messages'),
  emptyState : document.getElementById('empty-state'),
  input   : document.getElementById('input'),
  sendBtn : document.getElementById('send-btn'),
  micBtn  : document.getElementById('mic-btn'),
  orbWrapper : document.getElementById('orb-wrapper'),
  orbStatus  : document.getElementById('orb-status'),
  memoryList  : document.getElementById('memory-list'),
  memoryEmpty : document.getElementById('memory-empty'),
  memoryCount : document.getElementById('memory-count'),
  healthPanel  : document.getElementById('health-panel'),
  healthToggle : document.getElementById('health-toggle'),
  healthClose  : document.getElementById('health-close'),
};
